package com.pojo;

// Generated Jun 12, 2018 3:28:23 PM by Hibernate Tools 3.4.0.CR1

/**
 * Adminregister generated by hbm2java
 */
public class Adminregister implements java.io.Serializable {

	private Integer id;
	private Role role;
	private String fname;
	private String lname;
	private String email;
	private Integer phoneno;
	private String password;

	public Adminregister() {
	}

	public Adminregister(Role role) {
		this.role = role;
	}

	public Adminregister(Role role, String fname, String lname, String email, Integer phoneno,String password) {
		this.role = role;
		this.fname = fname;
		this.lname = lname;
		this.email = email;
		this.phoneno = phoneno;
		this.password=password;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public int getPhoneno() {
		return this.phoneno;
	}

	public void setPhoneno(Integer phoneno) {
		this.phoneno = phoneno;
	}

}
