package com.pojo;

// Generated Jun 12, 2018 3:28:23 PM by Hibernate Tools 3.4.0.CR1

/**
 * Feedback generated by hbm2java
 */
public class Feedback implements java.io.Serializable {

	private Integer fid;
	private Patientregister patientregister;
	private String message;
	private String doctorName;

	public Feedback() {
	}

	public Feedback(Patientregister patientregister, String message, String doctorName) {
		this.patientregister = patientregister;
		this.message = message;
		this.doctorName = doctorName;
	}

	public Integer getFid() {
		return this.fid;
	}

	public void setFid(Integer fid) {
		this.fid = fid;
	}

	public Patientregister getPatientregister() {
		return this.patientregister;
	}

	public void setPatientregister(Patientregister patientregister) {
		this.patientregister = patientregister;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getDoctorName() {
		return this.doctorName;
	}

	public void setDoctorName(String doctorName) {
		this.doctorName = doctorName;
	}

}
