package com.pojo;

// Generated Jun 12, 2018 3:28:23 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Patientregister generated by hbm2java
 */
public class Patientregister implements java.io.Serializable {

	private Integer pid;
	private Role role;
	private String fname;
	private String lname;
	private String email;
	private String password;
	private String problem;
	private String gender;
	private String phoneno;
	private Set feedbacks = new HashSet(0);
	private Set applydoctors = new HashSet(0);

	public Patientregister() {
	}

	public Patientregister(Role role, String fname, String lname, String email, String password, String problem,
			String gender,String phoneno, Set feedbacks, Set applydoctors) {
		this.role = role;
		this.fname = fname;
		this.lname = lname;
		this.email = email;
		this.password = password;
		this.problem = problem;
		this.gender = gender;
		this.phoneno = phoneno;
		this.feedbacks = feedbacks;
		this.applydoctors = applydoctors;
	}

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getProblem() {
		return this.problem;
	}

	public void setProblem(String problem) {
		this.problem = problem;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getPhoneno() {
		return this.phoneno;
	}

	public void setPhoneno(String phoneno1) {
		this.phoneno = phoneno;
	}

	public Set getFeedbacks() {
		return this.feedbacks;
	}

	public void setFeedbacks(Set feedbacks) {
		this.feedbacks = feedbacks;
	}

	public Set getApplydoctors() {
		return this.applydoctors;
	}

	public void setApplydoctors(Set applydoctors) {
		this.applydoctors = applydoctors;
	}

}
