package com.pojo;

// Generated Jun 12, 2018 3:28:23 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private Integer id;
	private String roleName;
	private Set patientregisters = new HashSet(0);
	private Adminregister adminregister;
	private Set doctorregisters = new HashSet(0);

	public Role() {
	}

	public Role(String roleName, Set patientregisters, Adminregister adminregister, Set doctorregisters) {
		this.roleName = roleName;
		this.patientregisters = patientregisters;
		this.adminregister = adminregister;
		this.doctorregisters = doctorregisters;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public Set getPatientregisters() {
		return this.patientregisters;
	}

	public void setPatientregisters(Set patientregisters) {
		this.patientregisters = patientregisters;
	}

	public Adminregister getAdminregister() {
		return this.adminregister;
	}

	public void setAdminregister(Adminregister adminregister) {
		this.adminregister = adminregister;
	}

	public Set getDoctorregisters() {
		return this.doctorregisters;
	}

	public void setDoctorregisters(Set doctorregisters) {
		this.doctorregisters = doctorregisters;
	}

}
